### ISSUE TITLE
Lesson 4.0 typo

### ISSUE THREAD

**Issue by RonyAllaw** [cmps253/design-architecture#25]
Sentence "is be to move" should be "is to move" :
<img width="474" alt="Lesson4_snippet" src="https://user-images.githubusercontent.com/72961423/112755413-42744480-8fe9-11eb-8a73-d002c2dbce5d.PNG">
Also, the same typo that occurred in lesson 3.0 (incomplete sentence) is present in this lesson.

**Comment by RonyAllaw** [comment]
Feel free to fix this issue if I don't.

**Comment by Hanaadany** [comment]
Done!
