### ISSUE TITLE
Wrong namespace used in Lesson 8, MultiLogger.cs

### ISSUE THREAD

**Issue by mxtm** [cmps253/design-architecture#4]
While attempting to compile Lesson 8, I received this error.

`MultiLogger.cs(14, 17): [CS0103] The name 'ConsoleLogger' does not exist in the current context`

It appears that this is because the file MultiLogger.cs in Lesson 8 uses the Lesson7.Solution2 namespace instead of Lesson8.Solution2.

**Comment by mbdeir** [comment]
Yes, you must have seen me fix it live before I officially started the meeting. But thanks anyway.

**Comment by mbdeir** [comment]
That lesson was not completed and not ready for sharing yet.
